apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-prod
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/mbaimuratov/biowatch.git
    targetRevision: prod
    path: infra/gitops/kafka/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-prod

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true