apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biowatch-root-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mbaimuratov/biowatch.git
    targetRevision: prod
    path: infra/gitops/apps/prod
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
