apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biowatch-dev-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: biowatch

  source:
    repoURL: https://github.com/mbaimuratov/biowatch.git
    targetRevision: main
    path: infra/gitops/environments/dev
    directory:
      include: "{sealed-secret.yaml,postgres-sealed-secret.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: biowatch-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
