---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: biowatch-dev-postgres-secret
  namespace: biowatch-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBE4NIXVTTJSRavwEzxkYj4Xr/DKh2VNwzdaMemqvPnqNJNGStm7fbVFreHRoOE39H6DA+o0sLutHezMul2/BL5IWOer5+OX2P8C8ehOPXuI1ucNrVYpyNdB49QqypkqEZYNYvXMfl5l+rfqMGNhqUwBVFicF6PY95rlcWfNRxNxcfc+IvrJRLpcfmAYzkyqPuQjnrfvm7WHHjp/VYpw779oCGJWJNScaeMdRcxMg4GnKV88zVD8M+hAgI8qi/nPEXJ7x/uaUxphpfqnsIWLiqzUrRNpaWKj2/cdseP8308div6m5wjdqYLaLNAKDj7EaXoq8VhCaqm4ZTURnsQEeCypYRQMUe8oD6yATPw7ROOEwywkgK8HtN5lJrlb9icZwH0eiMWTxPOErwOLnGOpmUUtU5tvcpS+0eNu37v4WkjIlB9X4rlgdgDrjKfn9X+su9ciHJzebD+9VVtZzurqUB7Fp+tzC8eqAeHM8vqyhUfdwN75aGiA0lU4kSJFKp3e/okSczCaxvTDTeuETQiEN5qm9o4vDraFwgoO7U/2gP+t4+7ES+ilEaLBrmFWWphoubThfOimLF49eHTkAqQZv6S0TZTzdo3cuMWYQVN1MWDdwio6sgMJfB42UBSLDG7jgVyPuitE7g+hQnHHcmKUS4e5LYYlwHf+gTp21tIp93v67v/kOI7Tu9KZuPBOvvdErCAE6IYZ6aRTw==
  template:
    metadata:
      name: biowatch-dev-postgres-secret
      namespace: biowatch-dev
