apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 1.0.0
    helm:
      valuesObject:
        watchNamespaces:
          - kafka-prod

  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-system

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true