apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biowatch-prod
  namespace: argocd
spec:
  project: biowatch

  sources:
    - repoURL: https://github.com/mbaimuratov/biowatch.git
      targetRevision: prod
      path: infra/helm/biowatch
      helm:
        valueFiles:
          - $values/infra/gitops/environments/prod/values.yaml
    - repoURL: https://github.com/mbaimuratov/biowatch.git
      targetRevision: prod
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: biowatch-prod

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
