image:
  repository: ghcr.io/mbaimuratov/biowatch
  tag: c0df6be3e15a9027e3d69394ddd40718fba5768d
  pullPolicy: IfNotPresent

app:
  environment: production
  kafka:
    enabled: true
    bootstrapServers: biowatch-kafka-kafka-bootstrap.kafka-prod.svc.cluster.local:9092
    clientId: biowatch-prod
    indexerTopic: biowatch.paper.ingested.v1
    indexerGroupId: biowatch-indexer

secret:
  create: false
  existingSecret: biowatch-secret

ingress:
  enabled: true
  className: nginx
  host: biowatch.local

networkPolicy:
  enabled: true
  ingressNamespace: ingress-nginx

api:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

worker:
  replicaCount: 2
  metrics:
    port: 9100
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

summaryWorker:
  enabled: true
  replicaCount: 1
  metrics:
    port: 9100
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

bot:
  enabled: true
  replicaCount: 1

scheduler:
  enabled: true
  replicaCount: 1
  intervalSeconds: 60

outboxPublisher:
  enabled: true
  replicaCount: 1

indexerConsumer:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

postgres:
  persistence:
    enabled: true
    size: 2Gi

elasticsearch:
  javaOpts: -Xms512m -Xmx512m
  persistence:
    enabled: true
    size: 4Gi
  resources:
    requests:
      cpu: 150m
      memory: 768Mi
    limits:
      cpu: "1"
      memory: 1536Mi
